# fly.toml app configuration file generated for rakesh-sinha-website-delicate-log-3445 on 2023-12-23T22:06:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rakesh-sinha-website-delicate-log-3445"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
